name = "pyPDPPartitioner"
package_name = "pyPDP"
author = "Yannik Mahlau and Dominik Woiwode"
author_email = "woiwode@tnt.uni-hannover.de"
description = ("A python implementation of "
               "'Explaining Hyperparameter Optimization via Partial Dependence Plots'"
               " by Moosbauer et al.")
version = "0.1.9"
license = "MIT"
url = "https://github.com/dwoiwode/py-pdp-partitioner"
