name: PyTest
on: [ push ]
jobs:
  pytest:
    name: PyTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Build package
        run: python -m build
      - name: Run pytest
        run: pytest tests